name: "build-docs"
description: "Generates html documentation using Sphinx"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: pip install . -r requirements_doc.txt
    - name: Fix sandbox "The SUID sandbox helper binary was found, but is not configured correctly"
      shell: bash
      run: |
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
    - name: Build documentation
      shell: bash
      working-directory: docs_src
      run: ./create_docs
