name: "build-docs"
description: "Generates html documentation using Sphinx"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: pip install . -r requirements_doc.txt
    - name: Install xvfb
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y xvfb
    - name: Build documentation
      shell: bash
      working-directory: docs_src
      run: ./create_docs
