#!/bin/bash
rm -rf ../docs
python3 docex_contour.py
python3 docex_guessRoots.py
python3 docex_guessRootSymmetry.py

sphinx-build -b html . ../docs

# clean up
rm -f *.gif
rm -f *.pdf
rm -f *.mov
rm -f *.mp4