name: publish

on:
  release:
    types: [created]

env:
    latest_python: 3.12

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
      with:
        python-version: ${{ env.latest_python }}
    - name: Install uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        version: "0.11.24"
    - name: Build docs
      uses: ./.github/actions/build-docs
      env:
        SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build wheel
      run: uv build
    - name: Publish
      run: uv publish
    - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
      with:
        commit_message: Autoupdate documentation
        file_pattern: docs/*
        branch: master

  test:
    needs: deploy
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: 
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get tag name
      id: get_tag_name
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "VERSION: ${GITHUB_REF/refs\/tags\/v/}"
        echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
    - name: Install cxroots from pip
      run: |
        VERSION=${{ steps.get_tag_name.outputs.VERSION }}
        pip install cxroots==$VERSION --uploaded-prior-to P3D
    - name: Test import cxroots
      run: python -c "import cxroots; print(cxroots.__version__)"
